# analyzer_config.yaml

# Основные директории для анализа
main_directories:
  models:
    description: "Модели данных"
    patterns: ["*.py"]
    exclude_patterns: ["__init__.py", "test_*.py"]
    priority: 1

  views:
    description: "Представления"
    patterns: ["*.py"]
    exclude_patterns: ["__init__.py", "test_*.py"]
    priority: 2

  templates:
    description: "Шаблоны"
    patterns: ["*.html", "*.htm"]
    exclude_patterns: []
    priority: 3

  static:
    description: "Статические файлы"
    patterns: ["*.js", "*.css"]
    exclude_patterns: ["*.min.js", "*.min.css"]
    priority: 4

# Общие исключения
excluded_patterns:
  - "__pycache__"
  - ".git"
  - ".idea"
  - "venv"
  - "migrations"
  - "tests"
  - ".env"
  - ".DS_Store"
  - "*.pyc"
  - "db.sqlite3"

# Настройки анализа
settings:
  max_depth: 5  # Максимальная глубина сканирования
  cache_results: true
  export_formats:
    - tree
    - json
    - markdown

# Описания файлов
file_descriptions:
  "urls.py": "URL маршрутизация"
  "models.py": "Определение моделей данных"
  "views.py": "Представления (логика обработки запросов)"
  "forms.py": "Формы для обработки данных"
  "admin.py": "Настройки админ-панели"
  "settings.py": "Настройки проекта"
  "signals.py": "Обработчики сигналов"
  "middleware.py": "Промежуточное ПО"
  "document.py": "Модель для работы с документами"
  "employee.py": "Модель сотрудников"
  "equipment.py": "Модель оборудования"
  "organization.py": "Модель организации"
  "position.py": "Модель должностей"
  "subdivision.py": "Модель подразделений"
  "department.py": "Модель отделов"
  "ajax.py": "Обработчики AJAX-запросов"
  "custom_dynamic_forms.js": "JavaScript для динамических форм"
  "admin_dependent_dropdowns.js": "JavaScript для зависимых выпадающих списков"
  "main.js": "Основной JavaScript файл"

# Настройки логирования
logging:
  filename: "django_analyzer.log"
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"