# Generated by Django 4.2.18 on 2025-01-23 20:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        verbose_name="Наименование структурного подразделения",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Сокращенное наименование",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Структурное подразделение",
                "verbose_name_plural": "Структурные подразделения",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Наименование отдела"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Сокращенное наименование",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="divisions",
                        to="core.department",
                        verbose_name="Структурное подразделение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отдел",
                "verbose_name_plural": "Отделы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=255, verbose_name="Полное наименование организации"
                    ),
                ),
                (
                    "short_name_ru",
                    models.CharField(
                        max_length=100,
                        verbose_name="Сокращенное наименование организации",
                    ),
                ),
                (
                    "requisites_ru",
                    models.TextField(
                        blank=True, verbose_name="Реквизиты на русском языке"
                    ),
                ),
                (
                    "name_by",
                    models.CharField(
                        max_length=255,
                        verbose_name="Наименование организации на белорусском языке",
                    ),
                ),
                (
                    "short_name_by",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Сокращенное наименование на белорусском языке",
                    ),
                ),
                (
                    "requisites_by",
                    models.TextField(
                        blank=True, verbose_name="Реквизиты на белорусском языке"
                    ),
                ),
                ("inn", models.CharField(max_length=9, verbose_name="УНП")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
                "ordering": ["short_name_ru"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Наименование должности"
                    ),
                ),
                (
                    "safety_instructions_numbers",
                    models.CharField(
                        blank=True,
                        help_text="Укажите номера инструкций через запятую",
                        max_length=500,
                        verbose_name="Номера инструкций по охране труда",
                    ),
                ),
                (
                    "electrical_safety_group",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "I"), (2, "II"), (3, "III"), (4, "IV"), (5, "V")],
                        help_text="Римская цифра от I до V",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Группа по электробезопасности",
                    ),
                ),
                (
                    "internship_period",
                    models.IntegerField(
                        blank=True,
                        help_text="Двузначная цифра (дни)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(99),
                        ],
                        verbose_name="Срок стажировки",
                    ),
                ),
                (
                    "contractor_instructions",
                    models.CharField(
                        blank=True,
                        help_text="Укажите номера инструкций через запятую",
                        max_length=500,
                        verbose_name="Инструкции по договору подряда",
                    ),
                ),
                (
                    "is_safety_responsible",
                    models.BooleanField(
                        default=False, verbose_name="Ответственный за охрану труда"
                    ),
                ),
                (
                    "is_electrical_personnel",
                    models.BooleanField(
                        default=False,
                        verbose_name="Является электротехническим персоналом",
                    ),
                ),
                (
                    "is_internship_supervisor",
                    models.BooleanField(
                        default=False,
                        help_text="Отметьте, если сотрудник может быть руководителем стажировки",
                        verbose_name="Является руководителем стажировки",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="core.department",
                        verbose_name="Структурное подразделение",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="core.division",
                        verbose_name="Отдел",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="core.organization",
                        verbose_name="Организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Должность",
                "verbose_name_plural": "Должности",
                "ordering": ["name"],
                "unique_together": {("organization", "department", "division", "name")},
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Отчество"
                    ),
                ),
                (
                    "personnel_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Табельный номер"
                    ),
                ),
                (
                    "employment_date",
                    models.DateField(verbose_name="Дата приема на работу"),
                ),
                (
                    "dismissal_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата увольнения"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="core.department",
                        verbose_name="Структурное подразделение",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="core.division",
                        verbose_name="Отдел",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="core.organization",
                        verbose_name="Организация",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="core.position",
                        verbose_name="Должность",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Наименование документа"
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("instruction", "Инструкция"),
                            ("protocol", "Протокол"),
                            ("certificate", "Удостоверение"),
                            ("order", "Приказ"),
                            ("other", "Прочее"),
                        ],
                        max_length=20,
                        verbose_name="Тип документа",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/%Y/%m/%d/", verbose_name="Файл"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.department",
                        verbose_name="Подразделение",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.division",
                        verbose_name="Отдел",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                        verbose_name="Организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ",
                "verbose_name_plural": "Документы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="division",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="divisions",
                to="core.organization",
                verbose_name="Организация",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="core.organization",
                verbose_name="Организация",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="division",
            unique_together={("department", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("organization", "name")},
        ),
    ]
