# Generated by Django 5.0.12 on 2025-03-29 05:51

import django.core.files.storage
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('short_name', models.CharField(blank=True, max_length=255, verbose_name='Сокращенное наименование')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('document_type', models.CharField(choices=[('internship_order', '🔖 Распоряжение о стажировке'), ('admission_order', '🔖 Распоряжение о допуске к самостоятельной работе'), ('knowledge_protocol', '📋 Протокол проверки знаний по охране труда'), ('doc_familiarization', '📝 Лист ознакомления с документами')], max_length=50, verbose_name='Тип документа')),
                ('template_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='media/document_templates/'), upload_to='document_templates/', verbose_name='Файл шаблона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_ru', models.CharField(max_length=255, verbose_name='Полное наименование (рус)')),
                ('short_name_ru', models.CharField(max_length=100, verbose_name='Краткое наименование (рус)')),
                ('full_name_by', models.CharField(max_length=255, verbose_name='Полное наименование (бел)')),
                ('short_name_by', models.CharField(max_length=100, verbose_name='Краткое наименование (бел)')),
                ('requisites_ru', models.TextField(blank=True, verbose_name='Реквизиты (рус)')),
                ('requisites_by', models.TextField(blank=True, verbose_name='Реквизиты (бел)')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['full_name_ru'],
            },
        ),
        migrations.CreateModel(
            name='SIZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование СИЗ')),
                ('classification', models.CharField(help_text='Маркировка СИЗ по защитным свойствам или конструктивным особенностям', max_length=100, verbose_name='Классификация (маркировка)')),
                ('unit', models.CharField(default='шт.', max_length=50, verbose_name='Единица измерения')),
                ('wear_period', models.PositiveIntegerField(default=12, help_text="0 означает 'До износа'", verbose_name='Срок носки в месяцах')),
            ],
            options={
                'verbose_name': 'Средство индивидуальной защиты',
                'verbose_name_plural': 'Средства индивидуальной защиты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_nominative', models.CharField(max_length=255, verbose_name='ФИО (именительный)')),
                ('full_name_dative', models.CharField(max_length=255, verbose_name='ФИО (дательный)')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('place_of_residence', models.TextField(verbose_name='Место проживания')),
                ('height', models.CharField(blank=True, choices=[('158-164 см', '158-164 см'), ('170-176 см', '170-176 см'), ('182-188 см', '182-188 см'), ('194-200 см', '194-200 см')], max_length=15, verbose_name='Рост')),
                ('clothing_size', models.CharField(blank=True, choices=[('44-46', '44-46'), ('48-50', '48-50'), ('52-54', '52-54'), ('56-58', '56-58'), ('60-62', '60-62'), ('64-66', '64-66')], max_length=5, verbose_name='Размер одежды')),
                ('shoe_size', models.CharField(blank=True, choices=[('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48')], max_length=2, verbose_name='Размер обуви')),
                ('is_contractor', models.BooleanField(default=False, verbose_name='Договор подряда')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.department', verbose_name='Отдел')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='directory.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['full_name_nominative'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(upload_to='generated_documents/%Y/%m/%d/', verbose_name='Файл документа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('document_data', models.JSONField(blank=True, default=dict, help_text='Данные, использованные для генерации документа', verbose_name='Данные документа')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создан пользователем')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='directory.employee', verbose_name='Сотрудник')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.documenttemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Сгенерированный документ',
                'verbose_name_plural': 'Сгенерированные документы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=255, verbose_name='Наименование оборудования')),
                ('inventory_number', models.CharField(max_length=100, unique=True, verbose_name='Инвентарный номер')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.department', verbose_name='Отдел')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='directory.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование документа')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.department', verbose_name='Отдел')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='directory.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='directory.organization', verbose_name='Организация'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_role', models.CharField(choices=[('chairman', '👑 Председатель комиссии'), ('member', '👤 Член комиссии'), ('secretary', '📝 Секретарь комиссии'), ('none', '❌ Не участвует в комиссии')], default='none', help_text='Укажите роль сотрудника в комиссии', max_length=10, verbose_name='Роль в комиссии')),
                ('contract_work_name', models.TextField(blank=True, help_text='Укажите наименование работы, выполняемой по договору подряда', verbose_name='🔨 Наименование работы по договору подряда')),
                ('contract_safety_instructions', models.CharField(blank=True, help_text='Укажите номера инструкций по охране труда для данного вида работ', max_length=255, verbose_name='⚠️ Инструкции по охране труда по договору подряда')),
                ('position_name', models.CharField(max_length=255, verbose_name='Название')),
                ('safety_instructions_numbers', models.CharField(blank=True, max_length=255, verbose_name='Номера инструкций по ОТ')),
                ('electrical_safety_group', models.CharField(blank=True, choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V')], max_length=4, verbose_name='Группа по электробезопасности')),
                ('internship_period_days', models.PositiveIntegerField(default=0, verbose_name='Срок стажировки (дни)')),
                ('is_responsible_for_safety', models.BooleanField(default=False, verbose_name='Ответственный за ОТ')),
                ('is_electrical_personnel', models.BooleanField(default=False, verbose_name='Электротехнический персонал')),
                ('can_be_internship_leader', models.BooleanField(default=False, verbose_name='Может быть руководителем стажировки')),
                ('can_sign_orders', models.BooleanField(default=False, help_text='Указывает, может ли сотрудник с этой должностью подписывать распоряжения', verbose_name='Может подписывать распоряжения')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='directory.department', verbose_name='Отдел')),
                ('documents', models.ManyToManyField(blank=True, related_name='positions', to='directory.document', verbose_name='Документы')),
                ('equipment', models.ManyToManyField(blank=True, related_name='positions', to='directory.equipment', verbose_name='Оборудование')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='directory.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Профессия/должность',
                'verbose_name_plural': 'Профессии/должности',
                'ordering': ['position_name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.position', verbose_name='Должность'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('organizations', models.ManyToManyField(help_text='🏢 Организации, к которым у пользователя есть доступ', related_name='user_profiles', to='directory.organization', verbose_name='Организации')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='SIZIssued',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата выдачи')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('wear_percentage', models.PositiveIntegerField(default=0, help_text='Укажите процент износа от 0 до 100', verbose_name='Процент износа')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость')),
                ('replacement_date', models.DateField(blank=True, null=True, verbose_name='Дата замены/списания')),
                ('is_returned', models.BooleanField(default=False, verbose_name='Возвращено')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Дата возврата')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('condition', models.CharField(blank=True, help_text='Условие, при котором выдано СИЗ', max_length=255, verbose_name='Условие выдачи')),
                ('received_signature', models.BooleanField(default=False, verbose_name='Подпись о получении')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_siz', to='directory.employee', verbose_name='Сотрудник')),
                ('siz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='directory.siz', verbose_name='СИЗ')),
            ],
            options={
                'verbose_name': 'Выданное СИЗ',
                'verbose_name_plural': 'Выданные СИЗ',
                'ordering': ['-issue_date', 'employee__full_name_nominative'],
            },
        ),
        migrations.CreateModel(
            name='StructuralSubdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('short_name', models.CharField(blank=True, max_length=255, verbose_name='Сокращенное наименование')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subdivisions', to='directory.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Структурное подразделение',
                'verbose_name_plural': 'Структурные подразделения',
                'ordering': ['name'],
                'unique_together': {('name', 'organization')},
            },
        ),
        migrations.AddField(
            model_name='position',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='directory.structuralsubdivision', verbose_name='Структурное подразделение'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.structuralsubdivision', verbose_name='Структурное подразделение'),
        ),
        migrations.AddField(
            model_name='employee',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.structuralsubdivision', verbose_name='Структурное подразделение'),
        ),
        migrations.AddField(
            model_name='document',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.structuralsubdivision', verbose_name='Структурное подразделение'),
        ),
        migrations.AddField(
            model_name='department',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='directory.structuralsubdivision', verbose_name='Структурное подразделение'),
        ),
        migrations.CreateModel(
            name='SIZNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('condition', models.CharField(blank=True, help_text="Например: 'При влажной уборке помещений', 'При работе на высоте' и т.д.", max_length=255, verbose_name='Условие выдачи')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siz_norms', to='directory.position', verbose_name='Профессия/должность')),
                ('siz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='norms', to='directory.siz', verbose_name='СИЗ')),
            ],
            options={
                'verbose_name': 'Норма выдачи СИЗ',
                'verbose_name_plural': 'Нормы выдачи СИЗ',
                'ordering': ['position', 'condition', 'order', 'siz__name'],
                'unique_together': {('position', 'siz', 'condition')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('position_name', 'organization', 'subdivision', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'organization', 'subdivision')},
        ),
    ]
