# Generated by Django 5.0.12 on 2025-02-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', 'XXXX_add_commission_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='contract_safety_instructions',
            field=models.TextField(blank=True, help_text='Укажите номера инструкций по охране труда для данного вида работ', verbose_name='⚠️ Инструкции по охране труда по договору подряда'),
        ),
        migrations.AddField(
            model_name='position',
            name='contract_work_name',
            field=models.CharField(blank=True, help_text='Укажите наименование работы, выполняемой по договору подряда', max_length=500, verbose_name='🔨 Наименование работы по договору подряда'),
        ),
    ]
