# Generated by Django 5.1.5 on 2025-02-01 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('short_name', models.CharField(blank=True, max_length=255, verbose_name='Сокращенное наименование')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_ru', models.CharField(max_length=255, verbose_name='Полное наименование (рус)')),
                ('requisites_ru', models.TextField(verbose_name='Реквизиты (рус)')),
                ('full_name_by', models.CharField(max_length=255, verbose_name='Полное наименование (бел)')),
                ('short_name_by', models.CharField(max_length=255, verbose_name='Сокращенное наименование (бел)')),
                ('requisites_by', models.TextField(verbose_name='Реквизиты (бел)')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=255, verbose_name='Наименование оборудования')),
                ('inventory_number', models.CharField(max_length=100, unique=True, verbose_name='Инвентарный номер')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='directory.department', verbose_name='Отдел')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='directory.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование документа')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='directory.department', verbose_name='Отдел')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='directory.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='directory.organization', verbose_name='Организация'),
        ),
        migrations.CreateModel(
            name='StructuralSubdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('short_name', models.CharField(blank=True, max_length=255, verbose_name='Сокращенное наименование')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', to='directory.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Структурное подразделение',
                'verbose_name_plural': 'Структурные подразделения',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=255, verbose_name='Название')),
                ('safety_instructions_numbers', models.CharField(blank=True, max_length=255, verbose_name='Номера инструкций по ОТ')),
                ('electrical_safety_group', models.CharField(blank=True, choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V')], max_length=4, verbose_name='Группа по электробезопасности')),
                ('internship_period_days', models.PositiveIntegerField(default=0, verbose_name='Срок стажировки (дни)')),
                ('is_responsible_for_safety', models.BooleanField(default=False, verbose_name='Ответственный за ОТ')),
                ('is_electrical_personnel', models.BooleanField(default=False, verbose_name='Электротехнический персонал')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='directory.department', verbose_name='Отдел')),
                ('documents', models.ManyToManyField(blank=True, related_name='positions', to='directory.document', verbose_name='Документы')),
                ('equipment', models.ManyToManyField(blank=True, related_name='positions', to='directory.equipment', verbose_name='Оборудование')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='directory.organization', verbose_name='Организация')),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='directory.structuralsubdivision', verbose_name='Структурное подразделение')),
            ],
            options={
                'verbose_name': 'Профессия/должность',
                'verbose_name_plural': 'Профессии/должности',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='subdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='directory.structuralsubdivision', verbose_name='Структурное подразделение'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_nominative', models.CharField(max_length=255, verbose_name='ФИО (именительный)')),
                ('full_name_dative', models.CharField(max_length=255, verbose_name='ФИО (дательный)')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('place_of_residence', models.TextField(verbose_name='Место проживания')),
                ('height', models.CharField(blank=True, choices=[('158-164 см', '158-164 см'), ('170-176 см', '170-176 см'), ('182-188 см', '182-188 см'), ('194-200 см', '194-200 см')], max_length=15, verbose_name='Рост')),
                ('clothing_size', models.CharField(blank=True, choices=[('44-46', '44-46'), ('48-50', '48-50'), ('52-54', '52-54'), ('56-58', '56-58'), ('60-62', '60-62'), ('64-66', '64-66')], max_length=5, verbose_name='Размер одежды')),
                ('shoe_size', models.CharField(blank=True, choices=[('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48')], max_length=2, verbose_name='Размер обуви')),
                ('is_contractor', models.BooleanField(default=False, verbose_name='Договор подряда')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='directory.department', verbose_name='Отдел')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='directory.organization', verbose_name='Организация')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='directory.position', verbose_name='Должность')),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='directory.structuralsubdivision', verbose_name='Структурное подразделение')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='subdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='directory.structuralsubdivision', verbose_name='Структурное подразделение'),
        ),
        migrations.AddField(
            model_name='department',
            name='subdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='directory.structuralsubdivision', verbose_name='Структурное подразделение'),
        ),
    ]
