# Generated by Django 5.1.5 on 2025-02-01 09:20

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='subdivision',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='organization', chained_model_field='organization', on_delete=django.db.models.deletion.CASCADE, to='directory.structuralsubdivision', verbose_name='Структурное подразделение'),
        ),
        migrations.AlterField(
            model_name='position',
            name='department',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='subdivision', chained_model_field='subdivision', null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.department', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='position',
            name='subdivision',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='organization', chained_model_field='organization', on_delete=django.db.models.deletion.CASCADE, to='directory.structuralsubdivision', verbose_name='Структурное подразделение'),
        ),
    ]
