# Generated by Django 5.1.5 on 2025-02-01 09:51

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_alter_department_subdivision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='short_name_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Сокращенное наименование (рус)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='subdivision',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='organization', chained_model_field='organization', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='directory.structuralsubdivision', verbose_name='Структурное подразделение'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='short_name_by',
            field=models.CharField(blank=True, max_length=255, verbose_name='Сокращенное наименование (бел)'),
        ),
    ]
