# Generated by Django 5.0.12 on 2025-03-29 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_add_can_sign_orders_to_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='directory.department', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='directory.structuralsubdivision', verbose_name='Структурное подразделение'),
        ),
    ]
