# Generated by Django 5.0.12 on 2025-02-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_profile'),
    ]

    operations = [
    ]
