# Generated by Django 5.0.12 on 2025-03-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_organization_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='siznorm',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='siznorm',
            constraint=models.UniqueConstraint(condition=models.Q(('condition', '')), fields=('position', 'siz'), name='unique_position_siz_empty_condition'),
        ),
        migrations.AddConstraint(
            model_name='siznorm',
            constraint=models.UniqueConstraint(condition=models.Q(('condition', ''), _negated=True), fields=('position', 'siz', 'condition'), name='unique_position_siz_with_condition'),
        ),
    ]
