# Generated by Django 5.0.12 on 2025-02-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_alter_profile_organizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='organizations',
            field=models.ManyToManyField(help_text='🏢 Организации, к которым у пользователя есть доступ', related_name='user_profiles', to='directory.organization', verbose_name='Организации'),
        ),
    ]
