# Generated by Django 5.0.12 on 2025-03-30 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_alter_siznorm_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='siznorm',
            name='unique_position_siz_empty_condition',
        ),
        migrations.RemoveConstraint(
            model_name='siznorm',
            name='unique_position_siz_with_condition',
        ),
        migrations.AlterUniqueTogether(
            name='siznorm',
            unique_together={('position', 'siz', 'condition')},
        ),
    ]
