# Generated by Django 5.0.12 on 2025-02-24 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_alter_profile_organizations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structuralsubdivision',
            name='level',
        ),
        migrations.RemoveField(
            model_name='structuralsubdivision',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='structuralsubdivision',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='structuralsubdivision',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='structuralsubdivision',
            name='tree_id',
        ),
    ]
