# Generated by Django 5.0.12 on 2025-02-25 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_remove_structuralsubdivision_level_and_more'),
        ('directory', '0008_create_demo_data'),
    ]

    operations = [
    ]
