# Generated by Django 5.0.12 on 2025-02-27 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_merge_20250225_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPECategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование категории СИЗ')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='directory.ppecategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория СИЗ',
                'verbose_name_plural': 'Категории СИЗ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PPEItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование СИЗ')),
                ('unit', models.CharField(blank=True, help_text="Например, 'шт', 'пара' и т.д.", max_length=50, verbose_name='Единица измерения')),
                ('default_period_months', models.PositiveIntegerField(default=12, help_text='Сколько месяцев обычно носится данное СИЗ', verbose_name='Срок носки (мес) по умолчанию')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ppe_items', to='directory.ppecategory', verbose_name='Категория СИЗ')),
            ],
            options={
                'verbose_name': 'СИЗ',
                'verbose_name_plural': 'СИЗ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PPEIssued',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField(verbose_name='Дата выдачи')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Количество')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_items', to='directory.employee', verbose_name='Сотрудник')),
                ('ppe_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.ppeitem', verbose_name='Выданное СИЗ')),
            ],
            options={
                'verbose_name': 'Выдача СИЗ',
                'verbose_name_plural': 'Выдачи СИЗ',
                'ordering': ['-date_issued'],
            },
        ),
        migrations.CreateModel(
            name='PositionPPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, help_text='Сколько единиц данного СИЗ полагается по норме', max_digits=5, verbose_name='Количество')),
                ('period_months', models.PositiveIntegerField(default=12, help_text='Раз в сколько месяцев подлежит замене.', verbose_name='Период замены (мес)')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppe_norms', to='directory.position', verbose_name='Должность')),
                ('ppe_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.ppeitem', verbose_name='СИЗ')),
            ],
            options={
                'verbose_name': 'Норма СИЗ для должности',
                'verbose_name_plural': 'Нормы СИЗ для должностей',
                'ordering': ['position', 'ppe_item'],
            },
        ),
    ]
