# Generated by Django 5.0.12 on 2025-03-01 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0011_employeeppeoverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование СИЗ')),
                ('classification', models.CharField(help_text='Маркировка СИЗ по защитным свойствам или конструктивным особенностям', max_length=100, verbose_name='Классификация (маркировка)')),
                ('unit', models.CharField(default='шт.', max_length=50, verbose_name='Единица измерения')),
                ('wear_period', models.PositiveIntegerField(default=12, help_text="0 означает 'До износа'", verbose_name='Срок носки в месяцах')),
            ],
            options={
                'verbose_name': 'Средство индивидуальной защиты',
                'verbose_name_plural': 'Средства индивидуальной защиты',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='positionppe',
            name='position',
        ),
        migrations.RemoveField(
            model_name='positionppe',
            name='ppe_item',
        ),
        migrations.RemoveField(
            model_name='ppecategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='ppeitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ppeissued',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='ppeissued',
            name='ppe_item',
        ),
        migrations.CreateModel(
            name='SIZNormGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Например: 'При влажной уборке помещений дополнительно:'", max_length=255, verbose_name='Название группы/условие')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок отображения')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siz_norm_groups', to='directory.position', verbose_name='Профессия/должность')),
            ],
            options={
                'verbose_name': 'Группа норм СИЗ',
                'verbose_name_plural': 'Группы норм СИЗ',
                'ordering': ['position', 'order', 'name'],
                'unique_together': {('position', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SIZNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siz_norms', to='directory.position', verbose_name='Профессия/должность')),
                ('siz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='norms', to='directory.siz', verbose_name='СИЗ')),
                ('group', models.ForeignKey(blank=True, help_text='Оставьте пустым для обычной нормы выдачи', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='norms', to='directory.siznormgroup', verbose_name='Группа норм/условие')),
            ],
            options={
                'verbose_name': 'Норма выдачи СИЗ',
                'verbose_name_plural': 'Нормы выдачи СИЗ',
                'ordering': ['position', 'group__order', 'order', 'siz__name'],
                'unique_together': {('position', 'siz', 'group')},
            },
        ),
        migrations.DeleteModel(
            name='EmployeePPEOverride',
        ),
        migrations.DeleteModel(
            name='PositionPPE',
        ),
        migrations.DeleteModel(
            name='PPECategory',
        ),
        migrations.DeleteModel(
            name='PPEIssued',
        ),
        migrations.DeleteModel(
            name='PPEItem',
        ),
    ]
