# Generated by Django 5.0.12 on 2025-04-13 17:20

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0011_add_commission_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='commission_role',
            field=models.CharField(choices=[('chairman', '👑 Председатель комиссии'), ('member', '👤 Член комиссии'), ('secretary', '📝 Секретарь комиссии'), ('none', '❌ Не участвует в комиссии')], default='none', help_text='Укажите роль сотрудника в комиссии', max_length=10, verbose_name='Роль в комиссии'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='commissionmember',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='document_type',
            field=models.CharField(choices=[('all_orders', '📝 Распоряжения о стажировке'), ('knowledge_protocol', '📋 Протокол проверки знаний по охране труда'), ('doc_familiarization', '📝 Лист ознакомления с документами'), ('siz_card', '🛡️ Карточка учета СИЗ'), ('personal_ot_card', '👤 Личная карточка по ОТ'), ('journal_example', '📒 Образец заполнения журнала')], max_length=50, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='template_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/document_templates/', location='D:\\YandexDisk\\OT_online\\media\\document_templates'), upload_to='', verbose_name='Файл шаблона'),
        ),
    ]
