# Generated by Django 5.0.12 on 2025-04-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_add_commission_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='last_maintenance_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего ТО'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='maintenance_history',
            field=models.JSONField(blank=True, default=list, verbose_name='История ТО'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='maintenance_period_days',
            field=models.PositiveIntegerField(default=365, verbose_name='Периодичность ТО (дней)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='maintenance_status',
            field=models.CharField(choices=[('operational', 'Исправно'), ('needs_maintenance', 'Требует ТО'), ('in_maintenance', 'На обслуживании'), ('out_of_order', 'Неисправно')], default='operational', max_length=20, verbose_name='Статус обслуживания'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='next_maintenance_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата следующего ТО'),
        ),
    ]
