# Generated by Django 5.0.12 on 2025-04-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0013_equipment_last_maintenance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='maintenance_history',
            field=models.JSONField(blank=True, default=list, help_text="Список записей: {'date': 'YYYY-MM-DD', 'comment': '...'}", verbose_name='История ТО'),
        ),
    ]
