# Generated by Django 5.0.12 on 2025-03-26 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0014_documenttemplate_alter_siznorm_options_and_more'),
        ('directory', '0015_document_models_only'),
    ]

    operations = [
    ]
