# Generated by Django 5.0.12 on 2025-04-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0017_migrate_employee_contract_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_contractor',
            field=models.BooleanField(default=False, help_text='Устаревшее поле, используйте contract_type', verbose_name='Договор подряда'),
        ),
    ]
