# Generated by Django 5.0.14 on 2025-04-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0020_medicalexaminationtype_medicalsettings_harmfulfactor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('candidate', 'Кандидат'), ('active', 'Оформлен'), ('maternity_leave', 'В декретном отпуске'), ('part_time', 'Совместитель'), ('fired', 'Уволен')], db_index=True, default='active', help_text='Текущий статус сотрудника в организации', max_length=20, verbose_name='Статус сотрудника'),
        ),
    ]
