# Generated by Django 5.0.14 on 2025-10-02 09:36

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0021_employee_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='full_name_dative',
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='template_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/document_templates/', location='G:\\Мой диск\\OT_online\\media\\document_templates'), upload_to='', verbose_name='Файл шаблона'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name_nominative',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
    ]
