# Generated by Django 5.0.14 on 2025-10-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0022_remove_full_name_dative'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='harmfulfactor',
            unique_together={('short_name',)},
        ),
        migrations.RemoveField(
            model_name='harmfulfactor',
            name='examination_type',
        ),
    ]
