# Generated by Django 5.0.14 on 2025-10-02 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0023_remove_examination_type_from_harmfulfactor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemedicalexamination',
            name='examination_type',
        ),
    ]
