# Generated by Django 5.0.14 on 2025-10-27 08:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0024_remove_examination_type_from_employeemedicalexamination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('question_text', models.TextField(verbose_name='Текст вопроса')),
                ('image', models.ImageField(blank=True, help_text='Иллюстрация к вопросу', null=True, upload_to='quiz/questions/', verbose_name='Изображение')),
                ('explanation', models.TextField(blank=True, help_text='Объяснение правильного ответа', verbose_name='Пояснение')),
                ('order', models.IntegerField(default=0, help_text='Для сортировки вопросов', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['category', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=200, verbose_name='Название квиза')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('quiz_type', models.CharField(choices=[('training', 'Обучение по теме'), ('exam', 'Экзамен')], default='training', max_length=20, verbose_name='Тип квиза')),
                ('questions_per_category', models.IntegerField(default=5, help_text='Для экзамена: сколько вопросов брать из каждой категории', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Вопросов из каждой категории')),
                ('pass_score', models.IntegerField(default=80, help_text='Минимальный процент правильных ответов для прохождения', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Проходной балл (%)')),
                ('random_order', models.BooleanField(default=True, verbose_name='Случайный порядок вопросов')),
                ('show_correct_answer', models.BooleanField(default=True, help_text='Показывать правильность ответа после каждого вопроса', verbose_name='Показывать правильный ответ сразу')),
                ('allow_skip', models.BooleanField(default=True, verbose_name='Разрешить пропускать вопросы')),
                ('attempts_count', models.IntegerField(default=0, verbose_name='Количество попыток')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Квиз',
                'verbose_name_plural': 'Квизы',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='QuizCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Например: Общие вопросы по охране труда', max_length=200, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, help_text='Краткое описание категории', verbose_name='Описание')),
                ('order', models.IntegerField(default=0, help_text='Меньшее число - выше в списке', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать ли эту категорию пользователям', verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория квиза',
                'verbose_name_plural': 'Категории квизов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('answer_text', models.TextField(verbose_name='Текст ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('order', models.IntegerField(default=0, help_text='Порядок отображения ответа', verbose_name='Порядок')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='directory.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['question', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершена'), ('abandoned', 'Прервана')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('total_questions', models.IntegerField(default=0, verbose_name='Всего вопросов')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='Правильных ответов')),
                ('skipped_questions', models.IntegerField(default=0, verbose_name='Пропущено вопросов')),
                ('score_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Результат (%)')),
                ('passed', models.BooleanField(default=False, verbose_name='Тест пройден')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='directory.quiz', verbose_name='Квиз')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Попытка прохождения',
                'verbose_name_plural': 'Попытки прохождения',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Для обучающих квизов - обязательно', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='directory.quizcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='directory.quizcategory', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильно')),
                ('is_skipped', models.BooleanField(default=False, verbose_name='Пропущен')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Время ответа')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='directory.quizattempt', verbose_name='Попытка')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.question', verbose_name='Вопрос')),
                ('selected_answer', models.ForeignKey(blank=True, help_text='NULL если вопрос пропущен', null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.answer', verbose_name='Выбранный ответ')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
                'ordering': ['answered_at'],
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
