# Generated by Django 5.0.14 on 2025-10-28 18:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0025_add_quiz_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created'], 'verbose_name': 'Экзамен', 'verbose_name_plural': 'Экзамены'},
        ),
        migrations.AlterModelOptions(
            name='quizcategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.AddField(
            model_name='quiz',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, help_text='Оставьте пустым, чтобы экзамен был доступен всем', related_name='assigned_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='Назначен пользователям'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='directory.quizcategory', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Для обучающих экзаменов - обязательно', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='directory.quizcategory', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='questions_per_category',
            field=models.IntegerField(default=5, help_text='Для экзамена: сколько вопросов брать из каждого раздела', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Вопросов из каждого раздела'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('training', 'Обучение по теме'), ('exam', 'Экзамен')], default='training', max_length=20, verbose_name='Тип экзамена'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название экзамена'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='directory.quiz', verbose_name='Экзамен'),
        ),
        migrations.AlterField(
            model_name='quizcategory',
            name='description',
            field=models.TextField(blank=True, help_text='Краткое описание раздела', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='quizcategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Показывать ли этот раздел пользователям', verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='quizcategory',
            name='name',
            field=models.CharField(help_text='Например: Общие вопросы по охране труда', max_length=200, verbose_name='Название раздела'),
        ),
    ]
