# Generated by Django 5.2.6 on 2025-10-30 08:17

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0028_quiz_is_category_training'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='is_category_training',
            field=models.BooleanField(default=False, help_text='������� ��� ������������� ��������� ���������� �� ����������.', verbose_name='����-���������� �� �������'),
        ),
        migrations.CreateModel(
            name='QuizAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен доступа')),
                ('valid_from', models.DateTimeField(help_text='Начало периода доступа', verbose_name='Действителен с')),
                ('valid_until', models.DateTimeField(help_text='Окончание периода доступа', verbose_name='Действителен до')),
                ('is_used', models.BooleanField(default=False, help_text='Токен становится использованным после первого запуска экзамена', verbose_name='Использован')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата использования')),
                ('description', models.CharField(blank=True, help_text='Дополнительная информация о токене', max_length=200, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, help_text='Можно деактивировать токен досрочно', verbose_name='Активен')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quiz_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Создал токен')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='directory.quiz', verbose_name='Экзамен')),
                ('user', models.ForeignKey(help_text='Пользователь, которому предоставлен доступ', on_delete=django.db.models.deletion.CASCADE, related_name='quiz_access_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Токен доступа к экзамену',
                'verbose_name_plural': 'Токены доступа к экзаменам',
                'ordering': ['-created'],
                'unique_together': {('quiz', 'user')},
            },
        ),
    ]
