# Generated by Django 5.2.6 on 2025-10-30 10:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0029_alter_quiz_is_category_training_quizaccesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizaccesstoken',
            name='allow_resume',
            field=models.BooleanField(default=True, help_text='Может ли пользователь продолжить экзамен после перерыва', verbose_name='Разрешить продолжение'),
        ),
        migrations.AddField(
            model_name='quizaccesstoken',
            name='current_attempts',
            field=models.IntegerField(default=0, verbose_name='Текущее количество попыток'),
        ),
        migrations.AddField(
            model_name='quizaccesstoken',
            name='max_attempts',
            field=models.IntegerField(default=1, help_text='Сколько раз можно начать экзамен по этому токену', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимум попыток'),
        ),
        migrations.AddField(
            model_name='quizaccesstoken',
            name='require_login',
            field=models.BooleanField(default=True, help_text='Должен ли пользователь авторизоваться для использования токена', verbose_name='Требовать авторизацию'),
        ),
        migrations.CreateModel(
            name='QuizQuestionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(help_text='Позиция вопроса в экзамене (начинается с 0)', verbose_name='Порядковый номер')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_orders', to='directory.quizattempt', verbose_name='Попытка')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Порядок вопроса',
                'verbose_name_plural': 'Порядок вопросов',
                'ordering': ['attempt', 'order'],
                'indexes': [models.Index(fields=['attempt', 'order'], name='directory_q_attempt_afdf76_idx')],
                'unique_together': {('attempt', 'order'), ('attempt', 'question')},
            },
        ),
    ]
