# Generated by Django 5.2.6 on 2025-10-31 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0030_quizaccesstoken_allow_resume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='category',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='is_category_training',
        ),
        migrations.AddField(
            model_name='quiz',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Выберите разделы, которые входят в этот экзамен', related_name='quizzes', to='directory.quizcategory', verbose_name='Разделы экзамена'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('training', 'Обучение по теме'), ('exam', 'Экзамен')], default='exam', max_length=20, verbose_name='Тип экзамена'),
        ),
    ]
