# Generated by Django 5.2.6 on 2025-10-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0031_remove_quiz_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('training', 'Тренировка'), ('exam', 'Экзамен')], default='exam', max_length=20, verbose_name='Тип экзамена'),
        ),
    ]
