# Generated by Django 5.2.6 on 2025-10-31 05:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0032_alter_quiz_quiz_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='exam_total_questions',
            field=models.IntegerField(default=10, help_text='Общее максимальное количество вопросов (если разделов много, ограничит итоговое количество)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='Максимум вопросов в экзамене'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='questions_per_category',
            field=models.IntegerField(default=5, help_text='Сколько случайных вопросов взять из КАЖДОГО раздела для итогового экзамена', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Вопросов из каждого раздела'),
        ),
    ]
