# Generated by Django 5.0.14 on 2025-11-01 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0033_alter_quiz_exam_total_questions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_type',
        ),
    ]
