# Generated by Django 5.0.14 on 2025-11-02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0034_remove_quiz_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='category',
            field=models.ForeignKey(
                blank=True,
                help_text='Указывается только для тренировок по разделам. NULL = итоговый экзамен',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='training_attempts',
                to='directory.quizcategory',
                verbose_name='Раздел тренировки'
            ),
        ),
    ]
