# Generated by Django 5.0.14 on 2025-11-08 06:33

import django.db.models.deletion
from django.db import migrations, models


def migrate_existing_categories(apps, schema_editor):
    """
    Мигрирует существующие связи Quiz-Category в новую промежуточную таблицу
    """
    Quiz = apps.get_model('directory', 'Quiz')
    QuizCategoryOrder = apps.get_model('directory', 'QuizCategoryOrder')

    for quiz in Quiz.objects.all():
        order_counter = 0
        # Получаем существующие разделы через старое M2M поле
        for category in quiz.categories.all():
            QuizCategoryOrder.objects.create(
                quiz=quiz,
                category=category,
                order=order_counter
            )
            order_counter += 1


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0035_add_category_to_quizattempt'),
    ]

    operations = [
        # Шаг 1: Создаем промежуточную модель QuizCategoryOrder
        migrations.CreateModel(
            name='QuizCategoryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Порядок отображения раздела в данном экзамене (меньшее число = выше)', verbose_name='Порядок в экзамене')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.quizcategory', verbose_name='Раздел')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.quiz', verbose_name='Экзамен')),
            ],
            options={
                'verbose_name': 'Раздел в экзамене',
                'verbose_name_plural': 'Разделы в экзамене',
                'ordering': ['order', 'category__name'],
                'unique_together': {('quiz', 'category')},
            },
        ),

        # Шаг 2: Мигрируем существующие данные из старой M2M таблицы
        migrations.RunPython(migrate_existing_categories, migrations.RunPython.noop),

        # Шаг 3: Удаляем старое M2M поле
        migrations.RemoveField(
            model_name='quiz',
            name='categories',
        ),

        # Шаг 4: Создаем новое M2M поле с through
        migrations.AddField(
            model_name='quiz',
            name='categories',
            field=models.ManyToManyField(
                blank=True,
                help_text='Выберите разделы, которые входят в этот экзамен',
                related_name='quizzes',
                through='directory.QuizCategoryOrder',
                to='directory.quizcategory',
                verbose_name='Разделы экзамена'
            ),
        ),
    ]
